//
//  Titles.swift
//  dead songs
//
//  Created by Michael Johnson on 8/15/22.
//

import Foundation


let Titles : [String] = [
    
        "100,000 Tons Of Steel",
        "All New Minglewood Blues",
        "Alligator",
        "And We Bid You Goodnight",
        "Around And Around",
        "Attics Of My Life",
        "Beat It On Down The Line",
        "Bertha",
        "Big Boss Man",
        "Big Railroad Blues",
        "Big River",
        "Black Muddy River",
        "Black Peter",
        "Black—throated Wind",
        "Blues For Allah",
        "Born Cross—eyed",
        "Box Of Rain",
        "Brokedown Palace",
        "Candyman",
        "Casey Jones",
        "Caution (do Not Stop On Tracks)",
        "China Cat Sunflower",
        "China Doll",
        "Cold Rain And Snow",
        "Cosmic Charlie",
        "Crazy Fingers",
        "Cream Puff War",
        "Cumberland Blues",
        "Dancing In The Streets",
        "Dark Hollow",
        "Dark Star",
        "Day Job",
        "Deal",
        "Death Don't Have No Mercy",
        "Dire Wolf",
        "Doin' That Rag",
        "Dupree's Diamond Blues",
        "Easy Wind",
        "El Paso",
        "Estimated Prophet",
        "Eyes Of The World",
        "Fire On The Mountain",
        "France",
        "Franklin's Tower",
        "Friend Of The Devil",
        "From The Heart Of Me",
        "Goin' Down The Road Feeling Bad",
        "Good Lovin'",
        "Good Morning, Little School Girl",
        "Greatest Story Ever Told",
        "Hard To Handle",
        "He's Gone",
        "Hell In A Bucket",
        "Help On The Way",
        "Here Comes Sunshine",
        "High Time",
        "Hurts Me Too",
        "I Know You Rider",
        "I Need A Miracle",
        "I Will Take You Home",
        "I've Been All Around This World",
        "If I Had The World To Give",
        "It Must Have Been The Roses",
        "It's All Over Now, Baby Blue",
        "Jack Straw",
        "Johnny B. Goode",
        "Just A Little Light",
        "Katie Mae",
        "Let It Grow",
        "Let Me Sing Your Blues Away",
        "Loose Lucy",
        "Mama Tried",
        "Me And Bobby McGee",
        "Me And My Uncle",
        "Mississippi Half—step Uptown Toodeloo",
        "Money, Money",
        "Morning Dew",
        "Mountains Of The Moon",
        "Mr. Charlie",
        "My Brother Esau",
        "New Minglewood Blues",
        "New Potato Caboose",
        "New Speedway Boogie",
        "Not Fade Away",
        "One More Saturday Night",
        "Operator",
        "Passenger",
        "Playing In The Band",
        "Pride Of Cucamonga",
        "Promised Land",
        "Ramble On Rose",
        "Ripple",
        "Rosemary",
        "Row Jimmy",
        "Saint Of Circumstance",
        "Samson And Delilah",
        "Scarlet Begonias",
        "Shakedown Street",
        "Ship Of Fools",
        "Sittin' On Top Of The World",
        "Slipknot!",
        "Smokestack Lightnin'",
        "St. Stephen",
        "Stagger Lee",
        "Stella Blue",
        "Sugar Magnolia",
        "Sugaree",
        "Sunrise",
        "Tennessee Jed",
        "Terrapin Station Medley",
        "That's It For The Other One",
        "The Eleven",
        "The Golden Road (to Unlimited Devotion)",
        "The Music Never Stopped",
        "Till The Morning Comes",
        "Touch Of Grey",
        "Truckin'",
        "Turn On Your Lovelight",
        "U.S. Blues",
        "Unbroken Chain",
        "Uncle John's Band",
        "Viola Lee Blues",
        "Wake Up Little Susie",
        "Weather Report Suite",
        "Wharf Rat",
        "What's Become Of The Baby"
]
